export const TOOGLE_PERSONS_ACTION = "TOOGLE_PERSONS";
export const INCREASE_AGE_ACTION = "INCREASE_AGE";
export const CHANGE_PERSON_NAME_ACTION = "CHANGE_PERSON_NAME";
export const DELETE_PERSON_ACTION = "DELETE_PERSON";

export const INCREASE_RAM_ACTION = "INCREASE_RAM";
export const RESET_RAM_ACTION = "RESET_RAM";
export const SIMULATE_ERROR_ACTION = "SIMULATE_ERROR";

export const GET_POSTS_ACTION = "GET_POSTS";
export const DELETE_POSTS_ACTION = "DELETE_POSTS";
export const FETCHING_ERROR_ACTION = "FETCHING_ERROR";

export const AUTH_START_ACTION = "AUTH_START";
export const AUTH_ERROR_ACTION = "AUTH_ERROR";
export const AUTH_SUCCESS_ACTION = "AUTH_SUCCESS";

export const AUTH_TOKEN_EXPIRED_ACTION = "AUTH_TOKEN_EXPIRED";

export const GET_ORDERS_ACTION = "GET_ORDERS";
export const GET_ORDERS_FAILED_ACTION = "GET_ORDERS_FAILED";
