export const TOOGLE_PERSONS_ACTION = "TOOGLE_PERSONS";
export const INCREASE_AGE_ACTION = "INCREASE_AGE";
export const CHANGE_PERSON_NAME_ACTION = "CHANGE_PERSON_NAME";
export const DELETE_PERSON_ACTION = "DELETE_PERSON";
